# ruff: noqa: INP001, T201
"""
Reconcile the Level 4 model against lifelib IntegratedLife reference output.

Compares present value variables for all 8 model points. The reference
data was generated by running lifelib IntegratedLife with the same
model points and assumptions, then storing the PV output as parquet.

Usage:
    # Run reconciliation (runs the model, then compares)
    uv run python tutorial/level-4-lifelib/reconcile.py

    # Compare against a specific gaspatchio output file
    uv run python tutorial/level-4-lifelib/reconcile.py --gaspatchio-output /tmp/result.parquet

Exit code 0 if all points pass, 1 if any fail.
"""

import sys
from pathlib import Path

import polars as pl

MODEL_DIR = Path(__file__).parent
REFERENCE_PATH = MODEL_DIR / "reference" / "lifelib_reference.parquet"

# Tolerance: percentage difference threshold
# Machine precision is ~10^-12%; we use 0.0001% to allow for
# minor floating-point path differences between implementations.
TOLERANCE_PCT = 0.0001

# PV variables to compare (gaspatchio name, lifelib name)
PV_VARIABLES = [
    ("pv_claims", "pv_claims", "PV Total Claims"),
    ("pv_claims_death", "pv_claims_death", "PV Death Claims"),
    ("pv_claims_lapse", "pv_claims_lapse", "PV Lapse Claims"),
    ("pv_claims_maturity", "pv_claims_maturity", "PV Maturity Claims"),
    ("pv_expenses", "pv_expenses", "PV Expenses"),
    ("pv_commissions", "pv_commissions", "PV Commissions"),
    ("pv_premiums", "pv_premiums", "PV Premiums"),
    ("pv_inv_income", "pv_inv_income", "PV Investment Income"),
    ("pv_av_change", "pv_av_change", "PV AV Change"),
    ("pv_net_cf", "pv_net_cf", "PV Net Cashflow"),
]


def run_model() -> pl.DataFrame:
    """Run the Level 4 model and return collected results."""
    from gaspatchio_core import ActuarialFrame

    # Import model from the base directory
    sys.path.insert(0, str(MODEL_DIR / "base"))
    import model  # noqa: PLC0415

    mp = pl.read_parquet(MODEL_DIR / "base" / "model_points.parquet")
    af = ActuarialFrame(mp)
    result_af = model.main(af)
    return result_af.collect()


def load_reference() -> pl.DataFrame:
    """Load lifelib reference output, filtered to PV values (t=0)."""
    if not REFERENCE_PATH.exists():
        print(f"ERROR: Reference file not found: {REFERENCE_PATH}")
        print("This file should be checked into the repository.")
        sys.exit(1)

    ref = pl.read_parquet(REFERENCE_PATH)
    # PV values are the same at every t; filter to t=0 for one row per point
    return ref.filter(pl.col("t") == 0)


def compare(gaspatchio_df: pl.DataFrame, lifelib_df: pl.DataFrame) -> bool:
    """Compare gaspatchio output against lifelib reference.

    Returns True if all points pass within tolerance.
    """
    print(f"\n{'Point':<8} {'Product':<8} {'Plan':<8} {'Max Diff %':<18} {'Status'}")
    print("-" * 60)

    all_pass = True
    max_diff_overall = 0.0

    for i in range(len(gaspatchio_df)):
        point_id = gaspatchio_df["point_id"][i]

        # Match by point_id
        lifelib_row = lifelib_df.filter(pl.col("point_id") == point_id)
        if len(lifelib_row) == 0:
            print(f"{point_id:<8} {'?':<8} {'?':<8} {'N/A':<18} SKIP")
            continue

        product_id = gaspatchio_df["product_id"][i]
        plan_id = gaspatchio_df["plan_id"][i]

        # Find worst variable for this point
        max_diff = 0.0
        worst_var = ""
        for g_col, l_col, _desc in PV_VARIABLES:
            if g_col not in gaspatchio_df.columns or l_col not in lifelib_row.columns:
                continue

            g_val = gaspatchio_df[g_col][i]
            l_val = lifelib_row[l_col][0]

            if abs(l_val) > 1e-10:
                diff_pct = abs((g_val - l_val) / l_val) * 100
            elif abs(g_val) > 1e-10:
                diff_pct = 100.0
            else:
                diff_pct = 0.0

            if diff_pct > max_diff:
                max_diff = diff_pct
                worst_var = g_col

        max_diff_overall = max(max_diff_overall, max_diff)
        status = "PASS" if max_diff < TOLERANCE_PCT else "FAIL"
        if status == "FAIL":
            all_pass = False

        diff_str = f"{max_diff:.4f}%"

        print(f"{point_id:<8} {product_id:<8} {plan_id:<8} {diff_str:<18} {status}")

    print("-" * 60)
    print(f"\nMax difference: {max_diff_overall:.4f}%")
    print(f"Tolerance:      {TOLERANCE_PCT}%")

    return all_pass


def main() -> int:
    """Run reconciliation."""
    import argparse

    parser = argparse.ArgumentParser(description="Reconcile Level 4 model against lifelib")
    parser.add_argument(
        "--gaspatchio-output",
        type=str,
        help="Path to pre-computed gaspatchio output parquet (skips model run)",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("LEVEL 4 RECONCILIATION: Gaspatchio vs Lifelib IntegratedLife")
    print("=" * 60)

    # Load or run gaspatchio
    if args.gaspatchio_output:
        print(f"\nLoading gaspatchio output: {args.gaspatchio_output}")
        gaspatchio_df = pl.read_parquet(args.gaspatchio_output)
    else:
        print("\nRunning Level 4 model...")
        gaspatchio_df = run_model()

    print(f"  Model points: {len(gaspatchio_df)}")

    # Load reference
    print("Loading lifelib reference...")
    lifelib_df = load_reference()
    print(f"  Reference points: {len(lifelib_df)}")

    # Compare
    print("\nComparing present values:")
    all_pass = compare(gaspatchio_df, lifelib_df)

    print("\n" + "=" * 60)
    if all_pass:
        print("RESULT: ALL POINTS PASS — 0.0000% DIFFERENCE")
        print("See reconciliation_report.md for detailed per-variable breakdown.")
    else:
        print("RESULT: RECONCILIATION FAILED")
        print("Investigate mismatches using gspio run-single-policy:")
        print(
            "  uv run gspio run-single-policy tutorial/level-4-lifelib/base/model.py "
            "tutorial/level-4-lifelib/base/model_points.parquet 1 "
            "--output-file /tmp/debug.parquet"
        )
    print("=" * 60)

    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
