changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🐞 Bug fixes
      labels:
        - bug
    - title: 🚀 Features and improvements
      labels:
        - enhancement
    - title: 📚 Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
