# SPDX-FileCopyrightText: 2026 Opio Inc.
#
# SPDX-License-Identifier: Apache-2.0

"""
What-If Scenario Analysis with Declarative Configs

This script demonstrates Gaspatchio's declarative config format for scenario shocks.
Instead of writing Python code to create shocks, you specify simple dict/JSON configs
that can be generated by LLMs from natural language questions.

Examples:
    # Run all examples
    uv run python appliedlife/dynamic_scenarios.py

    # Run specific example
    uv run python appliedlife/dynamic_scenarios.py --example mortality
    uv run python appliedlife/dynamic_scenarios.py --example lapse
    uv run python appliedlife/dynamic_scenarios.py --example combined
    uv run python appliedlife/dynamic_scenarios.py --example stress

    # Custom config from JSON
    uv run python appliedlife/dynamic_scenarios.py --config '[{"id": "BASE"}, {"id": "TEST", "shocks": [{"table": "mortality", "multiply": 1.5}]}]'
"""

import argparse
import json
import sys
from pathlib import Path

import polars as pl

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from gaspatchio_core import ActuarialFrame, Table
from gaspatchio_core.scenarios import parse_scenario_config, describe_scenarios

ASSUMPTIONS_DIR = Path(__file__).parent / "assumptions"


# =============================================================================
# EXAMPLE CONFIGS - Translating natural language questions to configs
# =============================================================================

# "What if mortality increases by 20%?"
MORTALITY_SENSITIVITY = [
    {"id": "BASE"},
    {"id": "MORT_UP_10", "shocks": [{"table": "mortality", "multiply": 1.1}]},
    {"id": "MORT_UP_20", "shocks": [{"table": "mortality", "multiply": 1.2}]},
    {"id": "MORT_UP_30", "shocks": [{"table": "mortality", "multiply": 1.3}]},
]

# "What if lapses are 50% lower or 50% higher?"
LAPSE_SENSITIVITY = [
    {"id": "BASE"},
    {"id": "LAPSE_DOWN_50", "shocks": [{"table": "lapse", "multiply": 0.5}]},
    {"id": "LAPSE_UP_50", "shocks": [{"table": "lapse", "multiply": 1.5}]},
]

# "What's the worst case if mortality is higher AND lapses drop?"
COMBINED_SCENARIOS = [
    {"id": "BASE"},
    {"id": "BEST_CASE", "shocks": [
        {"table": "mortality", "multiply": 0.9},
        {"table": "lapse", "multiply": 1.1},
    ]},
    {"id": "WORST_CASE", "shocks": [
        {"table": "mortality", "multiply": 1.2},
        {"table": "lapse", "multiply": 0.8},
    ]},
]

# "Run standard regulatory stress scenarios"
STRESS_SCENARIOS = [
    {"id": "BASE"},
    {"id": "MORT_PANDEMIC", "shocks": [{"table": "mortality", "multiply": 1.5}]},
    {"id": "LAPSE_MASS", "shocks": [{"table": "lapse", "multiply": 2.0}]},
    {"id": "NO_DECREMENTS", "shocks": [
        {"table": "mortality", "set": 0.0},
        {"table": "lapse", "set": 0.0},
    ]},
]


def load_base_tables() -> dict[str, Table]:
    """Load assumption tables that can be shocked."""
    mortality_df = pl.read_parquet(ASSUMPTIONS_DIR / "mortality_select.parquet")
    lapse_df = pl.read_parquet(ASSUMPTIONS_DIR / "lapse_rates.parquet")

    tables = {
        "mortality": Table(
            name="mortality",
            source=mortality_df,
            dimensions={
                "table_id": "table_id",
                "attained_age": "attained_age",
                "duration": "duration",
            },
            value="mort_rate",
        ),
        "lapse": Table(
            name="lapse",
            source=lapse_df,
            dimensions={"duration": "duration", "lapse_id": "lapse_id"},
            value="lapse_rate",
        ),
    }
    return tables


def run_what_if_analysis(config: list[dict], tables: dict[str, Table]) -> pl.DataFrame:
    """
    Run what-if analysis using declarative config.

    Args:
        config: Scenario configuration (list of dicts)
        tables: Dict of base assumption tables

    Returns:
        DataFrame with scenario results
    """
    # Parse config to shock objects
    scenarios = parse_scenario_config(config)

    # Show scenario description (audit trail)
    print("\n" + "=" * 60)
    print("SCENARIO CONFIGURATION")
    print("=" * 60)
    description = describe_scenarios(scenarios, output_format="text")
    print(description)

    # For each scenario, apply shocks and compute a simple metric
    results = []
    for scenario_id, shocks in scenarios.items():
        # Start with base tables
        scenario_tables = tables.copy()

        # Apply shocks to relevant tables
        for shock in shocks:
            if shock.table in scenario_tables:
                scenario_tables[shock.table] = scenario_tables[shock.table].with_shock(shock)

        # Compute example metric: sum of mortality rates for ages 60-80, duration 0
        mort_table = scenario_tables["mortality"]
        sample_mortality = 0.0
        for age in range(60, 81):
            # Lookup mortality rate
            rate = mort_table.lookup(
                table_id=pl.lit("T3275"),
                attained_age=pl.lit(age),
                duration=pl.lit(0),
            )
            # Rate is a ColumnProxy - we need to evaluate it
            # For simplicity, use the underlying expression
            try:
                sample_df = pl.DataFrame({"x": [1]}).with_columns(rate.alias("rate"))
                sample_mortality += sample_df["rate"][0]
            except Exception:
                pass

        # Compute lapse metric: sum of lapse rates for durations 0-10
        lapse_table = scenario_tables["lapse"]
        sample_lapse = 0.0
        for dur in range(11):
            rate = lapse_table.lookup(
                duration=pl.lit(dur),
                lapse_id=pl.lit("L001"),
            )
            try:
                sample_df = pl.DataFrame({"x": [1]}).with_columns(rate.alias("rate"))
                sample_lapse += sample_df["rate"][0]
            except Exception:
                pass

        results.append({
            "scenario_id": scenario_id,
            "sum_mort_60_80": sample_mortality,
            "sum_lapse_0_10": sample_lapse,
            "n_shocks": len(shocks),
        })

    return pl.DataFrame(results)


def run_example(name: str, config: list[dict]) -> None:
    """Run a named example and display results."""
    print("\n" + "=" * 80)
    print(f"EXAMPLE: {name}")
    print("=" * 80)

    print("\nConfig (JSON):")
    print(json.dumps(config, indent=2))

    tables = load_base_tables()
    results = run_what_if_analysis(config, tables)

    print("\n" + "=" * 60)
    print("RESULTS")
    print("=" * 60)
    print(results)

    # Calculate impact vs BASE
    if "BASE" in results["scenario_id"].to_list():
        base_mort = results.filter(pl.col("scenario_id") == "BASE")["sum_mort_60_80"][0]
        base_lapse = results.filter(pl.col("scenario_id") == "BASE")["sum_lapse_0_10"][0]

        print("\n" + "=" * 60)
        print("IMPACT vs BASE")
        print("=" * 60)

        impact = results.with_columns([
            ((pl.col("sum_mort_60_80") - base_mort) / base_mort * 100).alias("mort_impact_pct"),
            ((pl.col("sum_lapse_0_10") - base_lapse) / base_lapse * 100).alias("lapse_impact_pct"),
        ]).select(["scenario_id", "mort_impact_pct", "lapse_impact_pct"])

        print(impact)


def main():
    """Run what-if scenario analysis examples."""
    parser = argparse.ArgumentParser(
        description="What-If Scenario Analysis with Declarative Configs",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python dynamic_scenarios.py                  # Run all examples
  python dynamic_scenarios.py --example mortality
  python dynamic_scenarios.py --example lapse
  python dynamic_scenarios.py --example combined
  python dynamic_scenarios.py --example stress
  python dynamic_scenarios.py --config '[{"id": "BASE"}, {"id": "SHOCK", "shocks": [{"table": "mortality", "multiply": 2.0}]}]'
        """,
    )
    parser.add_argument(
        "--example",
        choices=["mortality", "lapse", "combined", "stress"],
        help="Run specific example",
    )
    parser.add_argument(
        "--config",
        type=str,
        help="Custom config as JSON string",
    )

    args = parser.parse_args()

    print("\n" + "=" * 80)
    print("WHAT-IF SCENARIO ANALYSIS")
    print("=" * 80)
    print("\nThis demonstrates Gaspatchio's declarative config format for scenario shocks.")
    print("Instead of writing Python code, you specify simple dict/JSON configs.")

    if args.config:
        # Parse custom config
        try:
            config = json.loads(args.config)
            run_example("CUSTOM", config)
        except json.JSONDecodeError as e:
            print(f"\nError parsing JSON config: {e}")
            sys.exit(1)
    elif args.example:
        # Run specific example
        examples = {
            "mortality": ("MORTALITY SENSITIVITY", MORTALITY_SENSITIVITY),
            "lapse": ("LAPSE SENSITIVITY", LAPSE_SENSITIVITY),
            "combined": ("COMBINED SCENARIOS", COMBINED_SCENARIOS),
            "stress": ("STRESS SCENARIOS", STRESS_SCENARIOS),
        }
        name, config = examples[args.example]
        run_example(name, config)
    else:
        # Run all examples
        run_example("MORTALITY SENSITIVITY", MORTALITY_SENSITIVITY)
        run_example("LAPSE SENSITIVITY", LAPSE_SENSITIVITY)
        run_example("COMBINED SCENARIOS", COMBINED_SCENARIOS)
        run_example("STRESS SCENARIOS", STRESS_SCENARIOS)

    print("\n" + "=" * 80)
    print("KEY TAKEAWAYS")
    print("=" * 80)
    print("""
1. DECLARATIVE CONFIGS: Define shocks as simple dicts, not Python code
   {"table": "mortality", "multiply": 1.2}

2. OPERATIONS: Three shock types
   - multiply: Scale by factor (e.g., 1.2 = +20%)
   - add: Add constant (e.g., 0.01 = +1%)
   - set: Replace with value (e.g., 0.0 = zero)

3. LLM-FRIENDLY: Natural language questions map to configs
   "What if mortality is 20% higher?" -> {"table": "mortality", "multiply": 1.2}

4. AUDIT TRAIL: Use describe_scenarios() for documentation
""")
    print("=" * 80 + "\n")


if __name__ == "__main__":
    main()
