# gaspatchio-core/bindings/python/gaspatchio_core/dsl/core.pyi
# Stub file for core DSL components to help static analysis tools

from typing import TYPE_CHECKING, Any, Callable, TypeVar, overload

import polars as pl

# --- Forward References and TypeVars ---
if TYPE_CHECKING:
    # Forward declare ActuarialFrame if it's used in signatures before definition
    _ActuarialFrame = TypeVar("_ActuarialFrame", bound="ActuarialFrame")
    _BaseProxy = TypeVar("_BaseProxy", bound="BaseProxy")
    _ExpressionProxy = TypeVar("_ExpressionProxy", bound="ExpressionProxy")
    # Import accessors only for type checking
    # Import common type hints used in signatures
    from ...typing import IntoExprColumn
    from ..accessors.date import DateColumnAccessor, DateFrameAccessor
    from ..accessors.finance import FinanceColumnAccessor, FinanceFrameAccessor

# --- Helper Stubs for Chaining/Namespaces ---
class WhenThen:
    def then(self, statement: Any) -> "WhenThenThen": ...

class WhenThenThen(WhenThen):
    def otherwise(self, statement: Any) -> "_ExpressionProxy": ...

class ExprNameNamespace:
    def keep(self) -> "_ExpressionProxy": ...
    def map(self, function: Callable[[str], str]) -> "_ExpressionProxy": ...
    def map_fields(self, function: Callable[[str], str]) -> "_ExpressionProxy": ...
    def prefix(self, prefix: str) -> "_ExpressionProxy": ...
    def suffix(self, suffix: str) -> "_ExpressionProxy": ...

# --- Basic Namespace Stubs ---
# These provide *some* typing for namespace access.
# They could be fleshed out more later or generated automatically.

class ExprDTProxy:
    # Add methods returning ExpressionProxy
    def year(self) -> "ExpressionProxy": ...
    def month(self) -> "ExpressionProxy": ...
    def day(self) -> "ExpressionProxy": ...
    def ordinal_day(self) -> "ExpressionProxy": ...
    def weekday(self) -> "ExpressionProxy": ...
    def week(self) -> "ExpressionProxy": ...
    def quarter(self) -> "ExpressionProxy": ...
    def hour(self) -> "ExpressionProxy": ...
    def minute(self) -> "ExpressionProxy": ...
    def second(self) -> "ExpressionProxy": ...
    def microsecond(self) -> "ExpressionProxy": ...
    def nanosecond(self) -> "ExpressionProxy": ...
    def timestamp(self, tu: str = ...) -> "ExpressionProxy": ...
    def total_days(self) -> "ExpressionProxy": ...  # Duration
    def total_hours(self) -> "ExpressionProxy": ...  # Duration
    def total_minutes(self) -> "ExpressionProxy": ...  # Duration
    def total_seconds(self) -> "ExpressionProxy": ...  # Duration
    def total_microseconds(self) -> "ExpressionProxy": ...  # Duration
    def total_nanoseconds(self) -> "ExpressionProxy": ...  # Duration
    def truncate(self, every: str, offset: str | None = ...) -> "ExpressionProxy": ...
    def round(self, every: str, offset: str | None = ...) -> "ExpressionProxy": ...
    def replace_time_zone(
        self, time_zone: str | None, ambiguous: str = ...
    ) -> "ExpressionProxy": ...
    def convert_time_zone(self, time_zone: str) -> "ExpressionProxy": ...
    def cast_time_unit(self, tu: str = ...) -> "ExpressionProxy": ...  # Duration
    def replace_time_unit(self, tu: str = ...) -> "ExpressionProxy": ...  # Duration
    def combine(self, time: Any, tu: str = ...) -> "ExpressionProxy": ...  # Date + Time
    def strftime(self, format: str) -> "ExpressionProxy": ...
    def offset_by(self, by: str) -> "ExpressionProxy": ...
    def month_start(self) -> "ExpressionProxy": ...
    def month_end(self) -> "ExpressionProxy": ...
    def base_utc_offset(self) -> "ExpressionProxy": ...
    def dst_offset(self) -> "ExpressionProxy": ...
    # Add more dt methods as needed...

class ExprStringProxy:
    # Add methods returning ExpressionProxy
    def contains(
        self, pattern: str | pl.Expr, literal: bool = ..., strict: bool = ...
    ) -> "ExpressionProxy": ...
    def starts_with(self, prefix: str | pl.Expr) -> "ExpressionProxy": ...
    def ends_with(self, suffix: str | pl.Expr) -> "ExpressionProxy": ...
    def extract(self, pattern: str, group_index: int = ...) -> "ExpressionProxy": ...
    def extract_all(self, pattern: str) -> "ExpressionProxy": ...
    def count_matches(self, pattern: str, literal: bool = ...) -> "ExpressionProxy": ...
    def replace(
        self,
        pattern: str | pl.Expr,
        value: str | pl.Expr,
        literal: bool = ...,
        n: int = ...,
    ) -> "ExpressionProxy": ...
    def replace_all(
        self, pattern: str | pl.Expr, value: str | pl.Expr, literal: bool = ...
    ) -> "ExpressionProxy": ...
    def strip_chars(self, matches: str | pl.Expr | None = ...) -> "ExpressionProxy": ...
    def strip_chars_start(
        self, matches: str | pl.Expr | None = ...
    ) -> "ExpressionProxy": ...
    def strip_chars_end(
        self, matches: str | pl.Expr | None = ...
    ) -> "ExpressionProxy": ...
    def strip_prefix(self, prefix: str | pl.Expr) -> "ExpressionProxy": ...
    def strip_suffix(self, suffix: str | pl.Expr) -> "ExpressionProxy": ...
    def ljust(self, width: int, fill_char: str = ...) -> "ExpressionProxy": ...
    def rjust(self, width: int, fill_char: str = ...) -> "ExpressionProxy": ...
    def zfill(self, alignment: int) -> "ExpressionProxy": ...
    def slice(
        self, offset: int | pl.Expr, length: int | pl.Expr | None = ...
    ) -> "ExpressionProxy": ...
    def to_decimal(self, inference_length: int = ...) -> "ExpressionProxy": ...
    def to_integer(self, base: int = ..., strict: bool = ...) -> "ExpressionProxy": ...
    def parse_int(
        self, base: int = ..., strict: bool = ...
    ) -> "ExpressionProxy": ...  # Alias
    def to_date(
        self,
        format: str | None = ...,
        strict: bool = ...,
        exact: bool = ...,
        cache: bool = ...,
    ) -> "ExpressionProxy": ...
    def to_datetime(
        self,
        format: str | None = ...,
        tu: str | None = ...,
        time_offset: str | None = ...,
        time_zone: str | None = ...,
        zulu: bool = ...,
        strict: bool = ...,
        exact: bool = ...,
        cache: bool = ...,
        ambiguous: str | pl.Expr = ...,
    ) -> "ExpressionProxy": ...
    def to_time(
        self,
        format: str | None = ...,
        strict: bool = ...,
        exact: bool = ...,
        cache: bool = ...,
    ) -> "ExpressionProxy": ...
    def split(self, by: str | pl.Expr, inclusive: bool = ...) -> "ExpressionProxy": ...
    def split_exact(
        self, by: str | pl.Expr, n: int, inclusive: bool = ...
    ) -> "ExpressionProxy": ...
    def splitn(self, by: str | pl.Expr, n: int) -> "ExpressionProxy": ...
    def json_decode(
        self, dtype: pl.DataType | None = ..., infer_schema_length: int | None = ...
    ) -> "ExpressionProxy": ...
    def json_path_match(self, json_path: str) -> "ExpressionProxy": ...
    def len_bytes(self) -> "ExpressionProxy": ...
    def len_chars(self) -> "ExpressionProxy": ...
    def to_lowercase(self) -> "ExpressionProxy": ...
    def to_uppercase(self) -> "ExpressionProxy": ...
    def to_titlecase(self) -> "ExpressionProxy": ...
    def encode(self, encoding: str) -> "ExpressionProxy": ...
    def decode(self, encoding: str, strict: bool = ...) -> "ExpressionProxy": ...
    def hex_encode(self) -> "ExpressionProxy": ...
    def hex_decode(self, strict: bool = ...) -> "ExpressionProxy": ...
    def base64_encode(self) -> "ExpressionProxy": ...
    def base64_decode(self, strict: bool = ...) -> "ExpressionProxy": ...
    def convert_encoding(
        self, from_encoding: str, to_encoding: str, strict: bool = ...
    ) -> "ExpressionProxy": ...
    # Add more str methods as needed...

class ExprListProxy:
    # Add methods returning ExpressionProxy
    def sum(self) -> "ExpressionProxy": ...
    def mean(self) -> "ExpressionProxy": ...
    def min(self) -> "ExpressionProxy": ...
    def max(self) -> "ExpressionProxy": ...
    def median(self) -> "ExpressionProxy": ...
    def std(self, ddof: int = ...) -> "ExpressionProxy": ...
    def var(self, ddof: int = ...) -> "ExpressionProxy": ...
    def len(self) -> "ExpressionProxy": ...
    def get(
        self, index: int | pl.Expr, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...
    def first(self) -> "ExpressionProxy": ...
    def last(self) -> "ExpressionProxy": ...
    def contains(self, item: Any) -> "ExpressionProxy": ...
    def join(
        self, separator: str | pl.Expr, ignore_nulls: bool = ...
    ) -> "ExpressionProxy": ...
    def arg_min(self) -> "ExpressionProxy": ...
    def arg_max(self) -> "ExpressionProxy": ...
    def diff(self, n: int = ..., null_behavior: str = ...) -> "ExpressionProxy": ...
    def shift(self, periods: int = ...) -> "ExpressionProxy": ...
    def slice(
        self, offset: int | pl.Expr, length: int | pl.Expr | None = ...
    ) -> "ExpressionProxy": ...
    def head(self, n: int | pl.Expr = ...) -> "ExpressionProxy": ...
    def tail(self, n: int | pl.Expr = ...) -> "ExpressionProxy": ...
    def reverse(self) -> "ExpressionProxy": ...
    def unique(self, maintain_order: bool = ...) -> "ExpressionProxy": ...
    def unique_stable(self) -> "ExpressionProxy": ...  # Alias for maintain_order=True
    def sort(
        self, descending: bool = ..., nulls_last: bool = ...
    ) -> "ExpressionProxy": ...
    def take(
        self, index: pl.Expr | list[int] | pl.Series, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...
    def gather(
        self, index: pl.Expr | list[int] | pl.Series, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...  # Alias
    def gather_every(self, n: int, offset: int = ...) -> "ExpressionProxy": ...
    def explode(self) -> "ExpressionProxy": ...  # Apply explode to list elements
    def all(self) -> "ExpressionProxy": ...  # Check if all boolean elements are true
    def any(self) -> "ExpressionProxy": ...  # Check if any boolean elements are true
    def set_intersection(self, other: pl.Expr) -> "ExpressionProxy": ...
    def set_union(self, other: pl.Expr) -> "ExpressionProxy": ...
    def set_difference(self, other: pl.Expr) -> "ExpressionProxy": ...
    def set_symmetric_difference(self, other: pl.Expr) -> "ExpressionProxy": ...
    def eval(self, expr: pl.Expr, parallel: bool = ...) -> "ExpressionProxy": ...
    # Add more list methods as needed...

class ExprArrProxy:  # Covers FixedSizeList namespace
    def sum(self) -> "ExpressionProxy": ...
    def mean(self) -> "ExpressionProxy": ...
    def min(self) -> "ExpressionProxy": ...
    def max(self) -> "ExpressionProxy": ...
    def std(self, ddof: int = ...) -> "ExpressionProxy": ...
    def var(self, ddof: int = ...) -> "ExpressionProxy": ...
    def len(self) -> "ExpressionProxy": ...
    def get(
        self, index: int | pl.Expr, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...
    def first(self) -> "ExpressionProxy": ...
    def last(self) -> "ExpressionProxy": ...
    def contains(self, item: Any) -> "ExpressionProxy": ...
    def join(
        self, separator: str | pl.Expr, ignore_nulls: bool = ...
    ) -> "ExpressionProxy": ...
    def arg_min(self) -> "ExpressionProxy": ...
    def arg_max(self) -> "ExpressionProxy": ...
    def diff(self, n: int = ..., null_behavior: str = ...) -> "ExpressionProxy": ...
    def shift(self, periods: int = ...) -> "ExpressionProxy": ...
    def slice(
        self, offset: int | pl.Expr, length: int | pl.Expr | None = ...
    ) -> "ExpressionProxy": ...
    def head(self, n: int | pl.Expr = ...) -> "ExpressionProxy": ...
    def tail(self, n: int | pl.Expr = ...) -> "ExpressionProxy": ...
    def reverse(self) -> "ExpressionProxy": ...
    def unique(self, maintain_order: bool = ...) -> "ExpressionProxy": ...
    def unique_stable(self) -> "ExpressionProxy": ...  # Alias for maintain_order=True
    def sort(
        self, descending: bool = ..., nulls_last: bool = ...
    ) -> "ExpressionProxy": ...
    def take(
        self, index: pl.Expr | list[int] | pl.Series, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...
    def gather(
        self, index: pl.Expr | list[int] | pl.Series, null_on_oob: bool = ...
    ) -> "ExpressionProxy": ...  # Alias
    def gather_every(self, n: int, offset: int = ...) -> "ExpressionProxy": ...
    def all(self) -> "ExpressionProxy": ...  # Check if all boolean elements are true
    def any(self) -> "ExpressionProxy": ...  # Check if any boolean elements are true
    def to_list(self) -> "ExpressionProxy": ...  # Convert FixedSizeList back to List
    # Add more array methods...

class ExprStructProxy:  # Placeholder for Struct namespace
    def field(self, name: str) -> "ExpressionProxy": ...
    def fields(self) -> list[str]: ...  # Returns list of names, not Expr
    def rename_fields(self, names: list[str]) -> "ExpressionProxy": ...
    def unnest(
        self,
    ) -> "ExpressionProxy": ...  # Should maybe return multiple Exprs or AF?
    def json_encode(self) -> "ExpressionProxy": ...
    # Add more struct methods...

class ExprCatProxy:  # Placeholder for Categorical namespace
    def set_ordering(self, ordering: str) -> "ExpressionProxy": ...
    # Add methods as needed...

class ExprBinProxy:  # Placeholder for Binary namespace
    def contains(self, literal: bytes | pl.Expr) -> "ExpressionProxy": ...
    def starts_with(self, sub: bytes | pl.Expr) -> "ExpressionProxy": ...
    def ends_with(self, sub: bytes | pl.Expr) -> "ExpressionProxy": ...
    def hex_encode(self) -> "ExpressionProxy": ...
    def hex_decode(self, strict: bool = ...) -> "ExpressionProxy": ...
    def base64_encode(self) -> "ExpressionProxy": ...
    def base64_decode(self, strict: bool = ...) -> "ExpressionProxy": ...
    # Add more binary methods...

# --- Base Proxy (Optional but can help structure) ---
class BaseProxy:
    _parent: "_ActuarialFrame | None"
    # Common methods/properties can go here if applicable
    def __init__(self, parent: "_ActuarialFrame | None" = ...) -> None: ...

# --- Main Proxy Classes ---
class ExpressionProxy(BaseProxy):
    _expr: pl.Expr
    _parent: "_ActuarialFrame | None"

    def __init__(
        self, expr: pl.Expr, parent: "_ActuarialFrame | None" = ...
    ) -> None: ...

    # --- Operators ---
    # Define operators explicitly for clarity
    @overload
    def __add__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __add__(
        self: "_BaseProxy", other: Any
    ) -> "_BaseProxy": ...  # Keep original type hint too
    def __add__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __sub__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __sub__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __sub__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __mul__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __mul__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __mul__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __truediv__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __truediv__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __truediv__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __floordiv__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __floordiv__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __floordiv__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __mod__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __mod__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __mod__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __pow__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __pow__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __pow__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __eq__(self, other: Any) -> "ExpressionProxy": ...  # type: ignore[override]
    @overload
    def __eq__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...  # type: ignore[override]
    def __eq__(self, other: Any) -> "ExpressionProxy": ...  # type: ignore[override]
    @overload
    def __ne__(self, other: Any) -> "ExpressionProxy": ...  # type: ignore[override]
    @overload
    def __ne__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...  # type: ignore[override]
    def __ne__(self, other: Any) -> "ExpressionProxy": ...  # type: ignore[override]
    @overload
    def __gt__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __gt__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __gt__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __ge__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __ge__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __ge__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __lt__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __lt__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __lt__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __le__(self, other: Any) -> "ExpressionProxy": ...
    @overload
    def __le__(self: "_BaseProxy", other: Any) -> "_BaseProxy": ...
    def __le__(self, other: Any) -> "ExpressionProxy": ...

    # --- Key Proxied Polars Expr methods --- (Most are now covered by specific sections below)
    # Add more methods based on usage and polars.Expr attributes
    def abs(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def sqrt(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def floor(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def ceil(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def round(
        self, decimals: int = ...
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def cast(
        self, dtype: pl.DataType, strict: bool = ...
    ) -> "ExpressionProxy": ...  # Keep essential ones
    def alias(self, name: str) -> "ExpressionProxy": ...  # Keep essential ones
    def filter(
        self, predicate: "ExpressionProxy | pl.Expr | bool"
    ) -> "ExpressionProxy": ...  # Keep essential ones
    def is_null(self) -> "ExpressionProxy": ...  # Keep essential ones
    def is_not_null(self) -> "ExpressionProxy": ...  # Keep essential ones
    def is_in(self, other: Any) -> "ExpressionProxy": ...  # Keep essential ones
    def shift(self, periods: int = ...) -> "ExpressionProxy": ...  # Keep essential ones
    def fill_null(self, value: Any) -> "ExpressionProxy": ...  # Keep essential ones
    def log(
        self, base: float = ...
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def log10(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def exp(
        self,
    ) -> (
        "ExpressionProxy"
    ): ...  # Covered by _NUMERIC_UNARY handling but needed for stub
    def skew(self, bias: bool = ...) -> "ExpressionProxy": ...  # Keep essential ones
    def kurtosis(
        self, fisher: bool = ..., bias: bool = ...
    ) -> "ExpressionProxy": ...  # Keep essential ones
    def unique(
        self, maintain_order: bool = ...
    ) -> "ExpressionProxy": ...  # Keep essential ones
    def value_counts(
        self, sort: bool = ..., parallel: bool = ...
    ) -> "ExpressionProxy": ...  # Keep essential ones
    # ... add more methods as needed
    # --- Namespaces ---
    @property
    def dt(self) -> ExprDTProxy: ...
    @property
    def str(self) -> ExprStringProxy: ...
    @property
    def list(self) -> ExprListProxy: ...
    @property
    def arr(self) -> ExprArrProxy: ...
    @property
    def struct(self) -> ExprStructProxy: ...
    @property
    def cat(self) -> ExprCatProxy: ...
    @property
    def bin(self) -> ExprBinProxy: ...
    # Add other namespaces like meta if needed
    # @property
    # def meta(self) -> Any: ... # Simple type for meta
    # --- Date Accessor ---
    @property
    def date(self) -> "DateColumnAccessor": ...
    # --- Finance Accessor ---
    @property
    def finance(self) -> "FinanceColumnAccessor": ...
    # --- Aggregations ---
    def std(self, ddof: int = ...) -> "ExpressionProxy": ...
    def var(self, ddof: int = ...) -> "ExpressionProxy": ...
    def median(self) -> "ExpressionProxy": ...
    def quantile(
        self, quantile: float | pl.Expr, interpolation: str = ...
    ) -> "ExpressionProxy": ...
    def agg_groups(self) -> "ExpressionProxy": ...  # Useful in group_by context
    def n_unique(self) -> "ExpressionProxy": ...
    def first(self) -> "ExpressionProxy": ...
    def last(self) -> "ExpressionProxy": ...

    # --- Window Functions ---
    def cum_sum(self, reverse: bool = ...) -> "ExpressionProxy": ...
    def cum_prod(self, reverse: bool = ...) -> "ExpressionProxy": ...
    def cum_min(self, reverse: bool = ...) -> "ExpressionProxy": ...
    def cum_max(self, reverse: bool = ...) -> "ExpressionProxy": ...
    def diff(self, n: int = ..., null_behavior: str = ...) -> "ExpressionProxy": ...
    def pct_change(self, n: int = ...) -> "ExpressionProxy": ...
    def rank(
        self, method: str = ..., reverse: bool = ..., seed: int | None = ...
    ) -> "ExpressionProxy": ...
    # TODO: Add rolling_* and ewm_* stubs if needed
    # --- Manipulations / Transformations ---
    def clip(
        self, min_value: Any | None = ..., max_value: Any | None = ...
    ) -> "ExpressionProxy": ...
    def drop_nulls(self) -> "ExpressionProxy": ...
    def drop_nans(self) -> "ExpressionProxy": ...
    def fill_nan(
        self, value: Any
    ) -> "ExpressionProxy": ...  # Already exists below? Check consistency
    def interpolate(self, method: str = ...) -> "ExpressionProxy": ...
    def lower_bound(self) -> "ExpressionProxy": ...
    def upper_bound(self) -> "ExpressionProxy": ...
    def replace(
        self, old: Any, new: Any, return_dtype: pl.DataType | None = ...
    ) -> "ExpressionProxy": ...  # Basic version
    def reverse(self) -> "ExpressionProxy": ...
    def set_sorted(self, descending: bool = ...) -> "ExpressionProxy": ...
    def sort(
        self, descending: bool = ..., nulls_last: bool = ...
    ) -> "ExpressionProxy": ...
    def arg_sort(
        self,
        descending: bool = ...,
        nulls_last: bool = ...,
        multithreaded: bool = ...,
        maintain_order: bool = ...,
    ) -> "ExpressionProxy": ...
    def top_k(self, k: int | pl.Expr, descending: bool = ...) -> "ExpressionProxy": ...
    def bottom_k(
        self, k: int | pl.Expr, descending: bool = ...
    ) -> "ExpressionProxy": ...
    def unique(
        self, maintain_order: bool = ...
    ) -> "ExpressionProxy": ...  # Already exists below? Check consistency
    def value_counts(
        self, sort: bool = ..., parallel: bool = ...
    ) -> "ExpressionProxy": ...  # Already exists below? Check consistency

    # --- Boolean / Comparison ---
    def is_duplicated(self) -> "ExpressionProxy": ...
    def is_first_distinct(self) -> "ExpressionProxy": ...
    def is_last_distinct(self) -> "ExpressionProxy": ...
    def is_finite(self) -> "ExpressionProxy": ...
    def is_infinite(self) -> "ExpressionProxy": ...
    def is_nan(self) -> "ExpressionProxy": ...
    def is_not_nan(self) -> "ExpressionProxy": ...
    # is_null, is_not_null, is_in already exist
    # --- Rolling Window Functions ---
    def rolling_sum(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_min(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_max(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_mean(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_std(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
        ddof: int = ...,
    ) -> "ExpressionProxy": ...
    def rolling_var(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
        ddof: int = ...,
    ) -> "ExpressionProxy": ...
    def rolling_median(
        self,
        window_size: str | int,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_quantile(
        self,
        quantile: float,
        interpolation: str = ...,
        window_size: str | int = ...,
        weights: list[float] | None = ...,
        min_periods: int | None = ...,
        center: bool = ...,
        by: str | None = ...,
        closed: str | None = ...,
    ) -> "ExpressionProxy": ...
    def rolling_skew(self, window_size: int, bias: bool = ...) -> "ExpressionProxy": ...

    # --- Exponentially Weighted Moving (EWM) Window Functions ---
    def ewm_mean(
        self,
        alpha: float | None = ...,
        com: float | None = ...,
        span: float | None = ...,
        half_life: float | str | None = ...,
        adjust: bool = ...,
        min_periods: int = ...,
        ignore_nulls: bool = ...,
    ) -> "ExpressionProxy": ...
    def ewm_std(
        self,
        alpha: float | None = ...,
        com: float | None = ...,
        span: float | None = ...,
        half_life: float | str | None = ...,
        adjust: bool = ...,
        bias: bool = ...,
        min_periods: int = ...,
        ignore_nulls: bool = ...,
    ) -> "ExpressionProxy": ...
    def ewm_var(
        self,
        alpha: float | None = ...,
        com: float | None = ...,
        span: float | None = ...,
        half_life: float | str | None = ...,
        adjust: bool = ...,
        bias: bool = ...,
        min_periods: int = ...,
        ignore_nulls: bool = ...,
    ) -> "ExpressionProxy": ...

    # --- Conditional Logic ---
    def when(
        self, condition: Any
    ) -> "WhenThen": ...  # Special return type for chaining
    def map_dict(
        self, mapping: dict, default: Any = ..., return_dtype: pl.DataType | None = ...
    ) -> "ExpressionProxy": ...

    # --- List/Array Operations (Direct on Expr) ---
    def explode(self) -> "ExpressionProxy": ...
    def flatten(self) -> "ExpressionProxy": ...  # Alias for explode

    # --- Hashing/Misc ---
    def hash(
        self, seed: int = ..., seed_1: int = ..., seed_2: int = ..., seed_3: int = ...
    ) -> "ExpressionProxy": ...
    def reinterpret(self, signed: bool = ...) -> "ExpressionProxy": ...
    def reshape(self, dims: tuple[int, ...]) -> "ExpressionProxy": ...
    def shrink_dtype(self) -> "ExpressionProxy": ...

    # --- Meta / Naming ---
    def name(self) -> "ExprNameNamespace": ...  # Special namespace return
    def keep_name(self) -> "ExpressionProxy": ...
    def prefix(self, prefix: str) -> "ExpressionProxy": ...
    def suffix(self, suffix: str) -> "ExpressionProxy": ...
    # meta property might be too complex for a simple stub here

class ColumnProxy(ExpressionProxy):
    name: str
    def __init__(self, name: str, parent: "_ActuarialFrame | None" = ...) -> None: ...
    # Inherits methods from ExpressionProxy, specific overrides can go here
    # --- Date Accessor ---
    @property
    def date(self) -> "DateColumnAccessor": ...
    # --- Finance Accessor ---
    @property
    def finance(self) -> "FinanceColumnAccessor": ...

# --- ActuarialFrame Stub ---
# Provide a basic definition for context
class ActuarialFrame:
    _df: pl.LazyFrame
    # Add key methods and attributes used in type hints or needed for context
    def __init__(self, data: Any = ..., mode: str = ..., **kwargs: Any) -> None: ...
    def __getitem__(self, key: str) -> ColumnProxy: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def collect(self, **kwargs: Any) -> pl.DataFrame: ...
    # Add other frequently used ActuarialFrame methods
    # --- Date Accessor ---
    @property
    def date(self) -> "DateFrameAccessor": ...
    # --- Finance Accessor ---
    @property
    def finance(self) -> "FinanceFrameAccessor": ...

# --- Accessor Stubs ---
# These are added manually to provide hints for the accessor pattern

class DateFrameAccessor:
    _parent: "ActuarialFrame"
    def __init__(self, parent: "ActuarialFrame") -> None: ...
    def create_timeline(
        self,
        start_date_col: str | pl.Expr | "ExpressionProxy",
        end_date_col: str | pl.Expr | "ExpressionProxy",
        freq: str = ...,
        closed: str = ...,
        date_unit: str = ...,
        time_unit: str | None = ...,
        time_zone: str | None = ...,
        new_col_name: str = ...,
    ) -> "ActuarialFrame": ...
    def add_duration(
        self,
        date_col: "IntoExprColumn",
        duration_str: str,
        new_col_name: str | None = ...,
    ) -> "ActuarialFrame": ...
    # Add other DateFrameAccessor methods here if needed

class DateColumnAccessor:
    _expr: pl.Expr
    _parent: "_ActuarialFrame | None"  # Can be None if expr is standalone
    def __init__(
        self, expr: pl.Expr, parent: "_ActuarialFrame | None" = ...
    ) -> None: ...
    def from_excel_serial(self, origin: str = ...) -> "ExpressionProxy": ...
    def yearfrac(
        self, end_date_expr: "IntoExprColumn", basis: str = ...
    ) -> "ExpressionProxy": ...
    def to_period(self, freq: str = ...) -> "ExpressionProxy": ...
    # Add other DateColumnAccessor methods here if needed

# --- Finance Accessors ---
class FinanceFrameAccessor:
    _parent: "ActuarialFrame"
    def __init__(self, parent: "ActuarialFrame") -> None: ...
    # Add other FinanceFrameAccessor methods here
    def present_value(
        self,
        cashflow_col: "IntoExprColumn",
        rate_col: "IntoExprColumn",
        period_col: "IntoExprColumn",
    ) -> "ExpressionProxy": ...

class FinanceColumnAccessor:
    _expr: pl.Expr
    _parent: "_ActuarialFrame | None"
    def __init__(
        self, expr: pl.Expr, parent: "_ActuarialFrame | None" = ...
    ) -> None: ...
    def discount(
        self, rate_expr: "IntoExprColumn", n_periods_expr: "IntoExprColumn"
    ) -> "ExpressionProxy": ...
    # Add other FinanceColumnAccessor methods here
