"""Base type stubs for common proxy elements."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, List

import polars as pl
from polars.type_aliases import PolarsDataType

# Import types used in signatures
if TYPE_CHECKING:
    # Import Polars namespace types for hinting accessors added by autopatch
    from polars.expr.array import ExprArray
    from polars.expr.binary import ExprBinary
    from polars.expr.categorical import ExprCategorical
    from polars.expr.dt import ExprDT
    from polars.expr.list import ExprList
    from polars.expr.string import ExprString
    from polars.expr.struct import ExprStruct

    # Import local types carefully
    from .expression_proxy import ExpressionProxy

# Base class for shared proxy methods/properties
class _BaseProxy:
    """Base stub containing methods/properties common to ColumnProxy and ExpressionProxy."""

    # --- Operator Overloads (returning ExpressionProxy) ---
    def __add__(self, other: Any) -> "ExpressionProxy": ...
    def __sub__(self, other: Any) -> "ExpressionProxy": ...
    def __mul__(self, other: Any) -> "ExpressionProxy": ...
    def __truediv__(self, other: Any) -> "ExpressionProxy": ...
    def __floordiv__(self, other: Any) -> "ExpressionProxy": ...
    def __mod__(self, other: Any) -> "ExpressionProxy": ...
    def __pow__(self, other: Any) -> "ExpressionProxy": ...
    def __eq__(self, other: Any) -> "ExpressionProxy": ...
    def __ne__(self, other: Any) -> "ExpressionProxy": ...
    def __lt__(self, other: Any) -> "ExpressionProxy": ...
    def __le__(self, other: Any) -> "ExpressionProxy": ...
    def __gt__(self, other: Any) -> "ExpressionProxy": ...
    def __ge__(self, other: Any) -> "ExpressionProxy": ...
    def __radd__(self, other: Any) -> "ExpressionProxy": ...
    def __rsub__(self, other: Any) -> "ExpressionProxy": ...
    def __rmul__(self, other: Any) -> "ExpressionProxy": ...
    def __rtruediv__(self, other: Any) -> "ExpressionProxy": ...
    def __rfloordiv__(self, other: Any) -> "ExpressionProxy": ...
    def __rmod__(self, other: Any) -> "ExpressionProxy": ...
    def __rpow__(self, other: Any) -> "ExpressionProxy": ...

    # --- Common Autopatched Methods/Namespaces (Returning ExpressionProxy) ---
    def alias(self, name: str) -> "ExpressionProxy": ...
    def cast(
        self, dtype: PolarsDataType, *, strict: bool = True
    ) -> "ExpressionProxy": ...
    def sum(self) -> "ExpressionProxy": ...
    def mean(self) -> "ExpressionProxy": ...
    def min(self) -> "ExpressionProxy": ...
    def max(self) -> "ExpressionProxy": ...
    def count(self) -> "ExpressionProxy": ...
    def is_null(self) -> "ExpressionProxy": ...
    def fill_null(self, value: Any) -> "ExpressionProxy": ...
    def unique(self) -> "ExpressionProxy": ...
    def sort(self, *, descending: bool = False) -> "ExpressionProxy": ...
    def head(self, n: int = 5) -> "ExpressionProxy": ...
    def tail(self, n: int = 5) -> "ExpressionProxy": ...
    def filter(self, predicate: "ExpressionProxy" | pl.Expr) -> "ExpressionProxy": ...
    def shift(self, periods: int = 1) -> "ExpressionProxy": ...
    def over(
        self,
        partition_by: str | list[str] | pl.Expr | list[pl.Expr],
        *,
        mapping_strategy: str = "join",
    ) -> "ExpressionProxy": ...
    def when(self, *predicates: "ExpressionProxy" | pl.Expr) -> "ExpressionProxy": ...
    def then(self, expr: Any) -> "ExpressionProxy": ...
    def otherwise(self, expr: Any) -> "ExpressionProxy": ...

    # --- Autopatched Unary Numeric Methods (Returning ExpressionProxy) ---
    def abs(self) -> "ExpressionProxy": ...
    def sign(self) -> "ExpressionProxy": ...
    def floor(self) -> "ExpressionProxy": ...
    def ceil(self) -> "ExpressionProxy": ...
    def round(self, decimals: int = 0) -> "ExpressionProxy": ...
    def round_sig_figs(self, sig_figs: int) -> "ExpressionProxy": ...
    def exp(self) -> "ExpressionProxy": ...
    def log(self, base: float = ...) -> "ExpressionProxy": ...
    def log1p(self) -> "ExpressionProxy": ...
    def ln(self) -> "ExpressionProxy": ...
    def log10(self) -> "ExpressionProxy": ...
    def sqrt(self) -> "ExpressionProxy": ...
    def cbrt(self) -> "ExpressionProxy": ...
    def gamma(self) -> "ExpressionProxy": ...
    def is_nan(self) -> "ExpressionProxy": ...
    def is_finite(self) -> "ExpressionProxy": ...
    def is_infinite(self) -> "ExpressionProxy": ...
    def is_not_nan(self) -> "ExpressionProxy": ...
    def is_not_null(self) -> "ExpressionProxy": ...

    # --- Namespaces (Accessors returning Namespace Proxies) ---
    @property
    def dt(self) -> "ExprDT": ...
    @property
    def str(self) -> "ExprString": ...
    @property
    def list(self) -> "ExprList": ...
    @property
    def arr(self) -> "ExprArray": ...
    @property
    def struct(self) -> "ExprStruct": ...
    @property
    def cat(self) -> "ExprCategorical": ...
    @property
    def bin(self) -> "ExprBinary": ...

    # Although __dir__ is added dynamically, including it helps tools
    def __dir__(self) -> List[str]: ...
