from __future__ import annotations

from typing import TYPE_CHECKING, Any, List, Optional, Union

import polars as pl

# Import accessor types (adjust paths if needed when they are created)
from ..accessors.date import DateColumnAccessor
from ..accessors.finance import FinanceColumnAccessor

# ... other accessors

if TYPE_CHECKING:
    from ..frame.base import ActuarialFrame

class ColumnProxy:
    """Represents a column within an ActuarialFrame.

    This class is not meant to be instantiated directly. Obtain instances
    through DataFrame indexing, e.g., `df['column_name']`.
    """

    name: str
    _parent: ActuarialFrame
    _date_accessor_instance: Optional[DateColumnAccessor]
    _finance_accessor_instance: Optional[FinanceColumnAccessor]

    # Known built-in accessors (add more as they are implemented)
    # @property
    # def date(self) -> DateColumnAccessor: ...
    # @property
    # def finance(self) -> FinanceColumnAccessor: ...

    def __init__(self, name: str, parent: ActuarialFrame) -> None:
        """Do not call directly."""
        ...

    def _to_expr(self) -> pl.Expr:
        """Convert this proxy to a Polars expression."""
        ...

    def __repr__(self) -> str: ...

    # --- Common Methods ---
    def alias(self, name: str) -> ExpressionProxy:
        """Rename the output of this expression."""
        ...

    def cast(self, dtype: pl.DataType, strict: bool = True) -> ExpressionProxy:
        """Cast the underlying expression to a different data type."""
        ...

    # --- Operators ---
    def __add__(self, other: Any) -> ExpressionProxy: ...
    def __sub__(self, other: Any) -> ExpressionProxy: ...
    def __mul__(self, other: Any) -> ExpressionProxy: ...
    def __truediv__(self, other: Any) -> ExpressionProxy: ...
    def __floordiv__(self, other: Any) -> ExpressionProxy: ...
    def __mod__(self, other: Any) -> ExpressionProxy: ...
    def __pow__(self, other: Any) -> ExpressionProxy: ...

    # Comparison operators
    def __eq__(self, other: Any) -> ExpressionProxy: ...
    def __ne__(self, other: Any) -> ExpressionProxy: ...
    def __lt__(self, other: Any) -> ExpressionProxy: ...
    def __le__(self, other: Any) -> ExpressionProxy: ...
    def __gt__(self, other: Any) -> ExpressionProxy: ...
    def __ge__(self, other: Any) -> ExpressionProxy: ...
    def __dir__(self) -> List[str]: ...
    @property
    def date(self) -> DateColumnAccessor: ...
    @property
    def finance(self) -> FinanceColumnAccessor: ...

class ExpressionProxy:
    """Represents a Polars expression derived from ActuarialFrame operations.

    This class is not meant to be instantiated directly. Obtain instances
    by applying operations to ColumnProxy objects or using ActuarialFrame
    methods like `df.floor('col')`.
    """

    _expr: pl.Expr
    _parent: ActuarialFrame
    _date_accessor_instance: Optional[DateColumnAccessor]
    _finance_accessor_instance: Optional[FinanceColumnAccessor]

    # Known built-in accessors (add more as they are implemented)
    # @property
    # def date(self) -> DateColumnAccessor: ...
    # @property
    # def finance(self) -> FinanceColumnAccessor: ...

    def __init__(self, expr: Union[pl.Expr, Any], parent: ActuarialFrame) -> None:
        """Do not call directly."""
        ...

    def _to_expr(self) -> pl.Expr:
        """Return the underlying Polars expression."""
        ...

    def __repr__(self) -> str: ...

    # --- Common Methods ---
    def alias(self, name: str) -> ExpressionProxy:
        """Rename the output of this expression."""
        ...

    def cast(self, dtype: pl.DataType, strict: bool = True) -> ExpressionProxy:
        """Cast the expression to a different data type."""
        ...

    # --- Operators ---
    def __add__(self, other: Any) -> ExpressionProxy: ...
    def __sub__(self, other: Any) -> ExpressionProxy: ...
    def __mul__(self, other: Any) -> ExpressionProxy: ...
    def __truediv__(self, other: Any) -> ExpressionProxy: ...
    def __floordiv__(self, other: Any) -> ExpressionProxy: ...
    def __mod__(self, other: Any) -> ExpressionProxy: ...
    def __pow__(self, other: Any) -> ExpressionProxy: ...

    # Comparison operators
    def __eq__(self, other: Any) -> ExpressionProxy: ...
    def __ne__(self, other: Any) -> ExpressionProxy: ...
    def __lt__(self, other: Any) -> ExpressionProxy: ...
    def __le__(self, other: Any) -> ExpressionProxy: ...
    def __gt__(self, other: Any) -> ExpressionProxy: ...
    def __ge__(self, other: Any) -> ExpressionProxy: ...
    def __dir__(self) -> List[str]: ...
    @property
    def date(self) -> DateColumnAccessor: ...
    @property
    def finance(self) -> FinanceColumnAccessor: ...
